---
title: "Articles"
---

These are my non-academic articles I have written over the past few years. I have included some student newspaper, professional blog, and personal substack posts.

## Student Newspaper Articles ##

Two Things can be Bad: On Iran, the United States, and Military Intervention.

[[Link]](https://themedium.ca/two-things-can-be-bad/)

US Democrats’ Internal Battles: The Future of the US Democratic Party Resides in the Current Trends.

[[Link]](https://themedium.ca/us-democrats-internal-battles/)

Opinion: Ukraine and Gaza are Different Fights in the same Struggle.

[[Link]](https://thevarsity.ca/2025/11/01/opinion-ukraine-and-gaza-are-different-fights-in-the-same-struggle)

## Substack Articles ##

My full Substack can be found [[Here]](https://substack.com/@cyrusgazdar).

Money Talks! Why American cities Are Decaying and What Can Be Done About it.

[[Link]](https://open.substack.com/pub/cyrusgazdar/p/money-talks?r=4n78pp&utm_medium=ios)

The Most Predictable Suprises: A Follow-Up to Ontario’s Premier Election.

[[Link]](https://open.substack.com/pub/cyrusgazdar/p/the-most-predictable-suprises?r=4n78pp&utm_medium=ios)

The Centre of the World: Russia, Ukraine, and International Liberalism

[[Link]](https://open.substack.com/pub/cyrusgazdar/p/the-centre-of-the-world?r=4n78pp&utm_medium=ios)

The Neo-Liberal Collapse in Canada: What the Hell Happened?

[[Link]](https://open.substack.com/pub/cyrusgazdar/p/the-neo-liberal-collapse-in-canada?r=4n78pp&utm_medium=ios)

## Professional Blog ##

Freedom via Authoritarianism? Have Bukele’s Reforms Improved El Salvador?

[[Link]](https://canadatheessential.com/bukele)

Opinion: On 2SLGBTQ+ Rights Canada is Great, But Not Perfect.

[[Link]](https://www.unicef.ca/en/blog/2slgbtq-rights-canada-great-not-perfect)