---
title: "Home"
---
Hey there! I am a graduating student at the University of Toronto Mississauga. My programs of study include Political Science, Historical Studies, & Global Perspectives. My interests and works cover a number of topics within International Relations and contemporary Atlantic History. This includes but is not limited to conflict studies, democratic studies, American history and culture, political theory, and comparative foreign policy.

My current project is utilizing multivariate data sets such as the [*Cross-National Time Series*](https://www.cntsdata.com/), [*Varieties of Democracy*](https://v-dem.net/), and others to more effectively operationalize political instability in empirical studies of civil war. I'm also completed the first prototype for but continue to work on my first dataset: the [*Compiled Democracy Index*](CDI.qmd).

Outside of school, I enjoy reading (more politics & history books!), watching tv shows, skating, and watching hockey.

## Education

**Simon Fraser University | Burnaby, British Columbia**

Masters of Arts in Political Science | Degree Expected 2027

**University of Toronto | Toronto, Ontario**

Honours Bachelors of Arts in Political Science | September 2022- June 2026

## Affiliations

Co-founder & Editor (Comparative Politics, Book Reviews), UTM Undergraduate Journal of Political Science.

## Research Publications

"Freed Bondage: How American Liberalism and Slavery Collided in Early American Politics." *UTM Undergraduate Journal of Political Science 1*, no. 1 (2026): 1-9. (In Review).


## Conferences

*United we Stand, Divided we Drive: How Highways Served as Racial Mechanisms in 20th-Century American Life,* **Presenter at the 2025
Prandium Conference**, Mississauga, April 7, 2025.

## Projects

### Foreign Aid-Voting Index (April 2026-Present)

***[FAVI Download](FAVI.qmd)***

This dataset trys to answer the question *how does foreign aid influence state voting alignment with P5 members at the United Nations?* The dataset comes with a couple of important variables, and also a series of secondary variables for improved testing. More information, alongside the dataset, can be found under the *"Datasets"* tab.

### Compiled Democracy Index (March 2026 - Present)

***[CDI Download](CDI.qmd)***

A dataset that complies raw and scaled data from four major democracy indices. The first edition is made and can be found alongside all its suplementary information under the *"Datasets"* tab.